import puppeteer from "puppeteer-core";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
const OUT = process.argv[2];
mkdirSync(OUT, { recursive: true });
const browser = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: "new", args: ["--hide-scrollbars", "--autoplay-policy=no-user-gesture-required"] });
const page = await browser.newPage();
// desktop hero closed + open + services contrast + finale video + build page
await page.setViewport({ width: 1440, height: 900 });
await page.goto("http://localhost:3450/", { waitUntil: "networkidle0" });
await new Promise(r => setTimeout(r, 2000));
await page.screenshot({ path: join(OUT, "d-closed.png") });
await page.evaluate(() => window.scrollTo({ top: 1900, behavior: "instant" }));
await new Promise(r => setTimeout(r, 700));
await page.screenshot({ path: join(OUT, "d-open.png") });
await page.evaluate(() => { const secs=[...document.querySelectorAll("section")]; const s=secs.find(x=>x.className.includes("bg-linen")); window.scrollTo({top: s.offsetTop + 1400, behavior:"instant"}); });
await new Promise(r => setTimeout(r, 900));
await page.screenshot({ path: join(OUT, "d-service.png") });
await page.evaluate(() => window.scrollTo({ top: document.body.scrollHeight - 1500, behavior: "instant" }));
await new Promise(r => setTimeout(r, 1400));
await page.screenshot({ path: join(OUT, "d-finale.png") });
await page.goto("http://localhost:3450/build-with-bluedoor/", { waitUntil: "networkidle0" });
await new Promise(r => setTimeout(r, 1600));
await page.screenshot({ path: join(OUT, "d-build.png") });
// mobile: closed, crack, open, arch plate
await page.setViewport({ width: 390, height: 844 });
await page.goto("http://localhost:3450/", { waitUntil: "networkidle0" });
await new Promise(r => setTimeout(r, 1500));
await page.screenshot({ path: join(OUT, "m-closed.png") });
await page.evaluate(() => window.scrollTo({ top: 500, behavior: "instant" }));
await new Promise(r => setTimeout(r, 700));
await page.screenshot({ path: join(OUT, "m-mid.png") });
await page.evaluate(() => window.scrollTo({ top: 1400, behavior: "instant" }));
await new Promise(r => setTimeout(r, 700));
await page.screenshot({ path: join(OUT, "m-open.png") });
await page.goto("http://localhost:3450/process/", { waitUntil: "networkidle0" });
await page.evaluate(() => { document.documentElement.style.scrollBehavior="auto"; for(const h of document.querySelectorAll("h2")) if(h.textContent.includes("unsupervised")) { h.scrollIntoView({block:"center"}); break; } });
await new Promise(r => setTimeout(r, 900));
await page.screenshot({ path: join(OUT, "m-supervision.png") });
await browser.close();
console.log("done");
